version: '3.8'

services:
  backend:
    build:
      context: ./backend   # Vérifiez que ce répertoire contient le Dockerfile
      dockerfile: Dockerfile # S'assurer que le nom du Dockerfile est bien spécifié
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db_tp_docker

  frontend:
    build:
      context: ./frontend  # Vérifiez que ce répertoire contient le Dockerfile
      dockerfile: Dockerfile # S'assurer que le nom du Dockerfile est bien spécifié
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/dist
    stdin_open: true

  db_tp_docker:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  phpmyadmin_tp_docker:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db_tp_docker
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db_tp_docker

volumes:
  db_data: